package: zip_install
version: '2.0.0'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/zip_install

requires:
    redaxo: '^5.18.0'
    php:
        version: '>=8.1'
        extensions: [fileinfo, zip]

pages:
    install/packages/zip_install:
        title: translate:title
        icon: rex-icon fa-upload
        perm: admin[]
        pjax: true  # hier aktivieren wir pjax
        
conflicts:
    packages:
        install/packages/upload: '<2.0.0' # wegen möglicher seitenüberschneidung

default_config:
    upload_max_size: 20 # in MB
    github_token: '' # für die GitHub API
