package: zip_install
version: '1.5.2'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/zip_install

requires:
    packages:
        install: '^2.1'
    redaxo: '^5.10' # benötigt mindestens REDAXO 5.10

    php:
        version: '>=7.4'
        extensions: [fileinfo, zip] # benötigt die PHP-Extensions zip und fileinfo

pages:
    install/packages/zip_upload:
        title: translate:title
    install/packages/zip_url:
        title: translate:url_title
perm: admin
