package: zip_install
version: '2.3.0'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/zip_install
live_mode: false

requires:
    redaxo: '^5.18.0'
    php:
        version: '>=8.1'
        extensions: [fileinfo, zip]

pages:
    install/zip_install:
        title: translate:title
        icon: rex-icon fa-solid fa-file-arrow-up
        perm: admin[]
        pjax: true
        subpages:
            upload:
                title: translate:zip_install_file_upload
                icon: rex-icon fa-solid fa-file-arrow-up
                perm: admin[]
            settings:
                title: translate:settings
                icon: rex-icon fa-cog
                perm: admin[]
        
conflicts:
    packages:
        install/packages/upload: '<2.0.0'

default_config:
    upload_max_size: 50
    github_token: ''  # Optional GitHub API Token für höheres Rate Limit
